# Generated by Django 3.2.4 on 2021-09-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='текст вопроса')),
                ('possible_answer', models.TextField(verbose_name='возможные варианты ответа')),
                ('question_type', models.IntegerField(verbose_name='тип вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='QuizeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=200, verbose_name='название опроса')),
                ('quiz_description', models.CharField(max_length=200, verbose_name='описание опроса')),
                ('quiz_start', models.DateTimeField(verbose_name='дата старта опроса')),
                ('quiz_end', models.DateTimeField(verbose_name='дата окончания опроса')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.IntegerField(verbose_name='ID пользователя')),
                ('answer', models.IntegerField(verbose_name='ответ на вопрос')),
                ('question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.question')),
                ('quiz_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.quizelist')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.question')),
                ('quiz_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.quizelist')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizelist'),
        ),
    ]
