# Generated by Django 3.2.4 on 2021-09-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizList',
            new_name='Quiz',
        ),
    ]
