# Generated by Django 3.2.4 on 2021-09-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_quizlist_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_end',
            field=models.DateField(verbose_name='дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_start',
            field=models.DateField(verbose_name='дата старта опроса'),
        ),
    ]
